name: flex_dropdown
description: This package enables you to easily implement dropdowns with custom styling, animations, and data sources to match your app's needs.
version: 0.2.0
homepage: https://github.com/Snapp-X/flex_dropdown

environment:
  sdk: '>=3.0.2 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
